version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - ssrf-canary
registries:
  ssrf-canary:
    type: terraform-registry
    url: "https://ssrf-target.iad.github.net"
    token: "dummy-token"
